### ISSUE TITLE
Error running worker request

### ISSUE THREAD

**Issue by ben-5555** [Shuffle/Shuffle#1848]
**Describe the bug**
We are using the current version 2.1.0. and have a shuffle running on a Docker Swarm with 4 nodes. The apps are distributed across all 4 nodes (SHUFFLE_APP_REPLICAS=4), which works quite well so far. Now we want to run the worker on all 4 nodes as well and set: SHUFFLE_SCALE_REPLICAS=4.
The workers are distributed across all 4 nodes. The workflows are started, but some of them get stuck during execution. We see these errors in the Orborus log:
2025/10/16 10:52:18 [DEBUG][05888998-9223-40cc-8913-06362131a70b] Ran worker from requests. Worker URL: http://shuffle-workers:33333/api/v1/execute. DEBUGGING:
```

docker service logs shuffle-workers 2>&1 -f | grep 05888998-9223-40cc-8913-06362131a70b

2025/10/16 10:52:19 [ERROR][c98bb605-288b-406e-a2ed-2389a88bb812] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": net/http: timeout awaiting response headers

2025/10/16 10:52:19 [ERROR][2fe609bf-581f-40ae-8610-be0514d18389] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": net/http: timeout awaiting response headers

2025/10/16 10:52:19 [ERROR][43310ce1-4d6a-40a1-9eb7-00cfa2a763af] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": net/http: timeout awaiting response headers

2025/10/16 10:52:20 [DEBUG][a98cf861-bcf0-4b13-b299-8d919d014ba8] Ran worker from requests. Worker URL: http://shuffle-workers:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep a98cf861-bcf0-4b13-b299-8d919d014ba8

2025/10/16 10:52:21 [ERROR][0a7f0d22-ad5e-428c-a536-509aaacd7f47] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": net/http: timeout awaiting response headers

2025/10/16 10:52:35 [ERROR] Backend connection failed for url 'http://shuffle-backend:5001/api/v1/workflows/queue', or is missing (500): {"success": false, "reason": "dial tcp 172.18.0.2:9200: connect: cannot assign requested address"}

2025/10/16 10:52:39 [DEBUG][734b74ec-9d44-443e-9283-e52d248738d1] Ran worker from requests. Worker URL: http://shuffle-workers:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep 734b74ec-9d44-443e-9283-e52d248738d1

2025/10/16 10:52:39 [ERROR] Backend connection failed for url 'http://shuffle-backend:5001/api/v1/workflows/queue', or is missing (500): {"success": false, "reason": "dial tcp 172.18.0.2:9200: connect: cannot assign requested address"}

2025/10/16 10:52:40 [DEBUG][3331dd6e-033c-443b-b35c-2f07c655fb12] Ran worker from requests. Worker URL: http://shuffle-workers:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep 3331dd6e-033c-443b-b35c-2f07c655fb12

2025/10/16 10:52:49 [DEBUG][4152b0ff-590e-433b-8c4b-ed0610a3975c] Ran worker from requests. Worker URL: http://shuffle-workers:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep 4152b0ff-590e-433b-8c4b-ed0610a3975c
```

**To Reproduce**
With SHUFFLE_SCALE_REPLICAS=4, the 4 workers sometimes get stuck. If we remove the variable SHUFFLE_SCALE_REPLICAS again, one worker is started and the workflows run through.
           
**Expected behavior**
We expected that the workflows would also be processed with 4 workers and, in the best case, run faster because there are more resources available.

**Comment by frikky** [comment]
@yashsinghcodes what are we doing about it?

**Comment by yashsinghcodes** [comment]
The possible fix for this issue, as discussed, is setting up memcached (correctly configured). We’ll have a call this week to see if it helps and will update this thread accordingly.

**Comment by salamander04** [comment]
Is this issue solved? I'm facing the same issue

**Comment by frikky** [comment]
> Is this issue solved? I'm facing the same issue

@yashsinghcodes

**Comment by ben-5555** [comment]
> The possible fix for this issue, as discussed, is setting up memcached (correctly configured). We’ll have a call this week to see if it helps and will update this thread accordingly.

I have still the issue. How have I configure `memcached` correctly?

**Comment by yashsinghcodes** [comment]
Hey @ben-5555 @salamander04 Can you make sure that the memcache is present in the correct networks which should be - 

```
shuffle
swarm_executions
```

**Comment by salamander04** [comment]
> Hey [@ben-5555](https://github.com/ben-5555) [@salamander04](https://github.com/salamander04) Can you make sure that the memcache is present in the correct networks which should be -
> 
> ```
> shuffle
> swarm_executions
> ```

from the available docker-compose.yml file memcache is not enabled (commented). With the issue that we have, do we have to enable line memcache?

**Comment by yashsinghcodes** [comment]
Yes, @salamander04 keep in mind this applies when you’re running multiple workers, so they can share the same cache with each other.

**Comment by ben-5555** [comment]
> > Hey [@ben-5555](https://github.com/ben-5555) [@salamander04](https://github.com/salamander04) Can you make sure that the memcache is present in the correct networks which should be -
> > ```
> > shuffle
> > swarm_executions
> > ```
> 
> from the available docker-compose.yml file memcache is not enabled (commented). With the issue that we have, do we have to enable line memcache?

This is my compose for memcache:

```
  memcached:
    image: memcached:latest
    container_name: shuffle-cache
    hostname: shuffle-cache
    command: memcached -m 2048 -c 2500
    environment:
      - MEMCACHED_MEMORY=2048
      - MEMCACHED_MAX_CONNECTIONS=2500
    ports:
      - 11211:11211
    networks:
      - shuffle
      - shuffle_swarm_executions
    deploy:
      resources:
        limits:
          memory: 2048M
```
If I set `SHUFFLE_SCALE_REPLICAS=4` in Orborus Compose I still get this errors and workflows are not executed until end:

```
2025/11/04 09:18:29 [DEBUG][d405f934-2ae9-4e23-9338-bd2a1d363ac3] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep d405f934-2ae9-4e23-9338-bd2a1d363ac3

2025/11/04 09:18:37 [DEBUG][fce83e28-4e5c-4553-b5df-81ff516dceba] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep fce83e28-4e5c-4553-b5df-81ff516dceba

2025/11/04 09:18:39 [DEBUG][0831b2d8-fe25-4104-a8b8-76bc38c5b028] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep 0831b2d8-fe25-4104-a8b8-76bc38c5b028

2025/11/04 09:18:48 [DEBUG][70b77386-ce30-4e6b-9965-413752337584] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:

docker service logs shuffle-workers 2>&1 -f | grep 70b77386-ce30-4e6b-9965-413752337584

2025/11/04 09:18:54 [ERROR][34fb81ed-a8f9-4bf9-a7c5-aac7a67b640d] Error running worker request to http://10.10.232.13:33333/api/v1/execute (1): Post "http://10.10.232.13:33333/api/v1/execute": net/http: timeout awaiting response headers

2025/11/04 09:19:06 [ERROR][63a42949-f0bb-44ef-83f8-d9417d514eaf] Error running worker request to http://10.10.232.13:33333/api/v1/execute (1): Post "http://10.10.232.13:33333/api/v1/execute": net/http: timeout awaiting response headers

```

**Comment by salamander04** [comment]
> > > Hey [@ben-5555](https://github.com/ben-5555) [@salamander04](https://github.com/salamander04) Can you make sure that the memcache is present in the correct networks which should be -
> > > ```
> > > shuffle
> > > swarm_executions
> > > ```
> > 
> > 
> > from the available docker-compose.yml file memcache is not enabled (commented). With the issue that we have, do we have to enable line memcache?
> 
> This is my compose for memcache:
> 
> ```
>   memcached:
>     image: memcached:latest
>     container_name: shuffle-cache
>     hostname: shuffle-cache
>     command: memcached -m 2048 -c 2500
>     environment:
>       - MEMCACHED_MEMORY=2048
>       - MEMCACHED_MAX_CONNECTIONS=2500
>     ports:
>       - 11211:11211
>     networks:
>       - shuffle
>       - shuffle_swarm_executions
>     deploy:
>       resources:
>         limits:
>           memory: 2048M
> ```
> 
> If I set `SHUFFLE_SCALE_REPLICAS=4` in Orborus Compose I still get this errors and workflows are not executed until end:
> 
> ```
> 2025/11/04 09:18:29 [DEBUG][d405f934-2ae9-4e23-9338-bd2a1d363ac3] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:
> 
> docker service logs shuffle-workers 2>&1 -f | grep d405f934-2ae9-4e23-9338-bd2a1d363ac3
> 
> 2025/11/04 09:18:37 [DEBUG][fce83e28-4e5c-4553-b5df-81ff516dceba] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:
> 
> docker service logs shuffle-workers 2>&1 -f | grep fce83e28-4e5c-4553-b5df-81ff516dceba
> 
> 2025/11/04 09:18:39 [DEBUG][0831b2d8-fe25-4104-a8b8-76bc38c5b028] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:
> 
> docker service logs shuffle-workers 2>&1 -f | grep 0831b2d8-fe25-4104-a8b8-76bc38c5b028
> 
> 2025/11/04 09:18:48 [DEBUG][70b77386-ce30-4e6b-9965-413752337584] Ran worker from requests. Worker URL: http://10.10.232.13:33333/api/v1/execute. DEBUGGING:
> 
> docker service logs shuffle-workers 2>&1 -f | grep 70b77386-ce30-4e6b-9965-413752337584
> 
> 2025/11/04 09:18:54 [ERROR][34fb81ed-a8f9-4bf9-a7c5-aac7a67b640d] Error running worker request to http://10.10.232.13:33333/api/v1/execute (1): Post "http://10.10.232.13:33333/api/v1/execute": net/http: timeout awaiting response headers
> 
> 2025/11/04 09:19:06 [ERROR][63a42949-f0bb-44ef-83f8-d9417d514eaf] Error running worker request to http://10.10.232.13:33333/api/v1/execute (1): Post "http://10.10.232.13:33333/api/v1/execute": net/http: timeout awaiting response headers
> ```

I still got same error after uncommentes memcached lines, @yashsinghcodes. but I only use **shuffle** for the networks.
If I add network swarm_execution or shuffle_swarm_execution, memcached service is invalid

```
root@soar:/home/ubuntu/Shuffle# docker compose down
service "memcached" refers to undefined network swarm_executions: invalid compose project
root@soar:/home/ubuntu/Shuffle# nano docker-compose.yml
root@soar:/home/ubuntu/Shuffle# docker compose down
service "memcached" refers to undefined network shuffle_swarm_executions: invalid compose project
``` 


```
shuffle-orborus     | 2025/11/06 09:24:01 [ERROR][d78234e4-d6c3-4f5e-8ab4-fb34039a3c93] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:25:01 [ERROR][32a35c91-56aa-4493-b3d0-684ac51e824b] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:26:02 [ERROR][594e3a72-9970-4b5e-aa15-afc2180cf799] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:27:02 [ERROR][05271d5c-6599-4cf4-9ba0-d00b76b4b088] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:28:03 [ERROR][2cf31553-e66e-48c7-b2a3-6545961a5fea] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:29:03 [ERROR][6a107f81-9ad8-451c-a4cc-82c1d1923f92] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:30:04 [ERROR][a35c1184-f3bc-4cd0-9372-d3605bebd9c4] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:31:04 [ERROR][f4ce0977-77b0-4f43-a7d7-499388fbb5e7] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
shuffle-orborus     | 2025/11/06 09:32:05 [ERROR][6c8f9373-9576-4bc0-9a14-82f57a816f1d] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
```

**Comment by yashsinghcodes** [comment]
@0x0elliot There is worker timeout issue, have we seen this before?

**Comment by yashsinghcodes** [comment]
@salamander04 Could you also share your full shuffle-orborus logs and the output of docker service ls? It seems like your issue is different from @ben-5555’s, so please create a new issue on GitHub for this.

**Comment by 0x0elliot** [comment]
timeouts might be a red herring. 

@salamander04 can you show me your backend logs? do you find any nil pointers?

**Comment by 0x0elliot** [comment]
> shuffle-orborus     | 2025/11/06 09:24:01 [ERROR][d78234e4-d6c3-4f5e-8ab4-fb34039a3c93] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving


this looks like a different issue caused by changed configs. Mind sharing the whole docker-compose for when server wasn't misbehaving?

**Comment by frikky** [comment]
> > shuffle-orborus     | 2025/11/06 09:24:01 [ERROR][d78234e4-d6c3-4f5e-8ab4-fb34039a3c93] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving
> 
> this looks like a different issue caused by changed configs. Mind sharing the whole docker-compose for when server wasn't misbehaving?

This typically happens if some services are removed & remade, while others are not. 

@0x0elliot do we have a way of refreshing DNS configs during runtime in Orborus (and apps)? Just thinking how rerouting will work when we eventually have to deal with worst case scenarios for this.

**Comment by 0x0elliot** [comment]
We have identified a cause for this issue. We are working on a fix, thank you for reporting it. It has something to do with docker depreciating how they handle attaching network in their API :)

**Comment by 0x0elliot** [comment]
Can you run `docker version` in your system? @salamander04 

Trying to see something.

**Comment by ben-5555** [comment]
Currently we using Docker 28.5.2. Last night an Auto Update installed Docker 29.0.0 and Shuffle did not start, many DNS and API errors. We rolled back to the latest 28.5.2 version and Shuffle is running with the known worker issue.

**Comment by 0x0elliot** [comment]
Checks out with what we observed. 

@ben-5555 @salamander04  if your workers are timing out, can you grep out "nil" in the backend logs? I am trying to see something.

**Comment by 0x0elliot** [comment]
Actually, I read your original issue again. Seems like backend isn't able to reach to opensearch.

Can you check if your opensearch instance is healthy?

**Comment by 0x0elliot** [comment]
Leaving this info here, so that it's helpful for anyone who found this issue while searching for it:

> shuffle-orborus     | 2025/11/06 09:24:01 [ERROR][d78234e4-d6c3-4f5e-8ab4-fb34039a3c93] Error running worker request to http://shuffle-workers:33333/api/v1/execute (1): Post "http://shuffle-workers:33333/api/v1/execute": dial tcp: lookup shuffle-workers on 127.0.0.11:53: server misbehaving

Our users who's machines upgraded docker overnight to version 29 noticed as issue where the shuffle_swarm_executions network was not getting attached to the containers. This was probably because of some API changes on docker's end. We went ahead and patched it however (updating orborus and worker to nightly should fix it).

@yashsinghcodes Please make a new release soon for a stable version. We have made a bunch of fixes that are still in nightly.

**Comment by ben-5555** [comment]
> Checks out with what we observed.
> 
> [@ben-5555](https://github.com/ben-5555) [@salamander04](https://github.com/salamander04) if your workers are timing out, can you grep out "nil" in the backend logs? I am trying to see something.

Today I pulled the latest container version and set `SHUFFLE_SCALE_REPLICAS=4`. The issue ist still the same. this lines are very often in my backend log:

```
$ docker logs -f shuffle-backend  | grep nil
2025/11/13 07:47:53 [WARNING] Failed to get current org : status: 405, error: Incorrect HTTP method for uri [/organizations/_doc/] and method [GET], allowed: [POST]
2025/11/13 07:47:54 [INFO][808cb27f-c2cf-4bdf-b4b6-a5a74c7092b5] Set workflowexecution based on new worker (>0.8.53) for workflow 966bbee6-1cda-4c1f-8684-fb9415580117. Actions: 14, Triggers: 0, Results: 14, Status: FINISHED
2025/11/13 07:47:54 [INFO][808cb27f-c2cf-4bdf-b4b6-a5a74c7092b5] Set workflowexecution based on new worker (>0.8.53) for workflow 966bbee6-1cda-4c1f-8684-fb9415580117. Actions: 14, Triggers: 0, Results: 14, Status: FINISHED
2025/11/13 07:47:54 [INFO][808cb27f-c2cf-4bdf-b4b6-a5a74c7092b5] Set workflowexecution based on new worker (>0.8.53) for workflow 966bbee6-1cda-4c1f-8684-fb9415580117. Actions: 14, Triggers: 0, Results: 14, Status: FINISHED
2025/11/13 07:47:55 [INFO][cb08c96c-ae67-4648-a146-5fac267aa8c1] Set workflowexecution based on new worker (>0.8.53) for workflow 966bbee6-1cda-4c1f-8684-fb9415580117. Actions: 14, Triggers: 0, Results: 14, Status: FINISHED
2025/11/13 07:47:55 [INFO][808cb27f-c2cf-4bdf-b4b6-a5a74c7092b5] Set workflowexecution based on new worker (>0.8.53) for workflow 966bbee6-1cda-4c1f-8684-fb9415580117. Actions: 14, Triggers: 0, Results: 14, Status: FINISHED
2025/11/13 07:47:55 [WARNING] Error in org get: status: 405, error: Incorrect HTTP method for uri [/organizations/_doc/] and method [GET], allowed: [POST]
```

It looks like we have a new issue with the latest container version. I see many service containers (independent from SHUFFLE_SCALE_REPLICAS) the status `exited - code 137`, e.g. email containers but email service is working:

<img width="733" height="449" alt="Image" src="https://github.com/user-attachments/assets/5f309dce-5b60-4ef3-9589-864a9b1eb1c0" />


Also some `shuffle-workers` and `shuffle-tools` are in the `exited - code 137` status.

**Comment by 0x0elliot** [comment]
This is getting pretty concerning :)

Please schedule a call for whenever you're free here: https://cal.com/aditya-shuffle

I need to know why these containers are exiting with a 137 all of a sudden.

**Comment by 0x0elliot** [comment]
Also, if workflows are merely getting slowed down with the timeouts, I won't give it much thought over than adding memcached to make the executions faster. Unless, you're not seeing any executions moving forward at all, ever.

Furthermore, We are already working on a few fixes to reduce these timeouts.

Regardless, I am opening a new issue to track the 137s. They are far more concerning to me.

**Comment by ben-5555** [comment]
> Also, if workflows are merely getting slowed down with the timeouts, I won't give it much thought over than adding memcached to make the executions faster. Unless, you're not seeing any executions moving forward.

Memcache is enabled for backend. ~~If I enable memcache for Orborus we have an issue with the swarm.~~
This is my memcache config:

```
  memcached:
    image: memcached:latest
    container_name: shuffle-cache
    hostname: shuffle-cache
    command: memcached -m 2048 -c 2500
    environment:
      - MEMCACHED_MEMORY=2048
      - MEMCACHED_MAX_CONNECTIONS=2500
    ports:
      - 11211:11211
    networks:
      - shuffle
      - shuffle_swarm_executions
    deploy:
      resources:
        limits:
          memory: 2048M
```

In the `backend` environment enabled with `SHUFFLE_MEMCACHED=shuffle-cache:11211`. With the **latest container** version **memcache** will also work with `orborus`.


> Regardless, I am opening a new issue to track the 137s. They are far more concerning to me.

Thanks.

**Comment by 0x0elliot** [comment]
Looks good chief! This should make your executions faster.

**Comment by 0x0elliot** [comment]
Had a call with @ben-5555. This issue came up because of a network misconfiguration. Taken care of.
