### ISSUE TITLE
Branch condition does not work when running execute_python action

### ISSUE THREAD

**Issue by yashsinghcodes** [Shuffle/Shuffle#1863]
The branch condition `equals` doesn’t work when it runs with the execute_python action.

**Comment by yashsinghcodes** [comment]
I'll get it fixed

**Comment by frikky** [comment]
> I'll get it fixed

Status? How does it work differently for this one 🤔

**Comment by yashsinghcodes** [comment]
Seems like this has been fixed not able to reproduce even with same input data.

**Comment by padel-0** [comment]
@yashsinghcodes you were able to reproduce this behaviour again today, am I right?

for your reference and as additional information, I pulled the latest docker image tags today (2025-11-18 @ 14:15 UTC) for all shuffle components (frontend, backend, orborus and memcached) and still have this issue...

my setup / newly created workflow:

1. Start Node: is a "Repeat back to me" node, with the following example data (contents of `Call`):  

   ```json
   {"id":101,"name":"Example Dataset","type":"root_object"}
   ```

2. the first branch ist working with **"Repeat back to me"** nodes:
   1. first node is called `Shuffle_Repeat_Data`, having the following code block:  

      ```py
      {%python%}

      import json
      nodevalue = r"""$debugger"""
      if not nodevalue:
      nodevalue = r"""{"sample": "string", "int": 1}"""
      
      jsondata = json.loads(nodevalue)
      print(jsondata)

      {%endpython%}
      ```

   2. which results to:  

      ```json
      {"id":101,"name":"Example Dataset","type":"root_object"}
      ```

   3. comes the branch condition:
      - source: `$shuffle_repeat_data.id`
      - operator: `equals`
      - destination: `101`

   4. which leads to the next node being executed

3. the second branch is working with a **"Execute python"** node:
   1. first node is called `Python_Repeat_data`, having the similar code block:

      ```py
      import json
      nodevalue = r"""$debugger"""
      if not nodevalue:
      nodevalue = r"""{"sample": "string", "int": 1}"""
      
      jsondata = json.loads(nodevalue)
      print(jsondata)
      ```

   2. which results to:

      ```json
      {"success":true,"message":{"id":101,"name":"Example Dataset","type":"root_object"}}
      ```

   3. comes again the same branch condition:
      - source: `$python_repeat_data.message.id`
      - operator: `equals`
      - destination: `101`

   4. which **DOES NOT** lead to executing the next node in line

so this leads to the usage of "Repeat back to me" nodes everywhere, where I would just use a simple "Execute python" node with syntax highlighting and better code readability instead ...
